ghost_cheking/checking/urls.py
import django.urls

import checking.views

app_name = 'checking'

urlpatterns = [
    django.urls.path('', checking.views.UploadFile.as_view(), name='upload_file'),
]

ghost_cheking/ghost_cheking/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.staticfiles.urls
import django.urls
from django.contrib import admin
from django.urls import path, include

import checking.urls
import intro_page.urls
import results.urls
import loading.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(intro_page.urls)),
    path('check/', include(checking.urls)),
    path('result/', include(results.urls)),
    path('load/', include(loading.urls))

]

if django.conf.settings.DEBUG:
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    urlpatterns += django.contrib.staticfiles.urls.staticfiles_urlpatterns()

if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        django.urls.path(
            '__debug__/',
            django.urls.include(debug_toolbar.urls),
        ),
    )

ghost_cheking/intro_page/urls.py
import django.urls

import intro_page.views

urlpatterns = [
    django.urls.path('', intro_page.views.intro, name='intro'),
]

ghost_cheking/loading/urls.py
import django.urls

import loading.views

app_name = 'loading'

urlpatterns = [
    django.urls.path('<int:a>', loading.views.progres, name='progres-bar'),
]

ghost_cheking/results/urls.py
import django.urls

import results.views

app_name = 'results'

urlpatterns = [
    django.urls.path('errors', results.views.errors, name='errors'),
    django.urls.path('all_done', results.views.all_done, name='all_done'),
]

ghost_cheking/loading/models.py
from django.db import models

# Create your models here.

ghost_cheking/results/models.py
from django.db import models

# Create your models here.

ghost_cheking/checking/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()
    file.widget.attrs["style"] = '''position: absolute;	z-index: -1; 	opacity: 0; 	display: block; 	
        width: 0;	height: 0;'''


def handle_uploaded_file(f):
    with open("media/upload/name.docx", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

ghost_cheking/checking/views.py
import django.shortcuts
from django.views.generic import TemplateView

from .forms import UploadFileForm, handle_uploaded_file

a = False


class UploadFile(TemplateView):
    TEMPLATE = "checking/add_file.html"

    def get(self, request, *args, **kwargs):
        form = UploadFileForm()
        context = {'form': form}
        return django.shortcuts.render(request, self.TEMPLATE, context)

    def post(self, request):
        global a
        form = UploadFileForm(request.POST, request.FILES)
        context = {'form': form}
        if form and form.is_valid():
            handle_uploaded_file(request.FILES["file"])
            if a:
                a = False
                return django.shortcuts.redirect("loading:progres-bar", 1)
            else:
                a = True
                return django.shortcuts.redirect("loading:progres-bar", 0)
        return django.shortcuts.render(request, self.TEMPLATE, context)

ghost_cheking/intro_page/views.py
import django.shortcuts


def intro(request):
    return django.shortcuts.render(request, 'intro_page/intro.html')

ghost_cheking/loading/views.py
import django.shortcuts


def progres(request, a):
    if a == 1:
        s = '/result/all_done'
    else:
        s = '/result/errors'
    return django.shortcuts.render(request, 'loading/loading.html', context={'link': s})

ghost_cheking/results/views.py
import django.shortcuts


def all_done(request):
    return django.shortcuts.render(request, 'results/all_done.html')


def errors(request):
    return django.shortcuts.render(request, 'results/errors.html')

ghost_cheking/templates/checking/add_file.html
{% load static %}
<!doctype html>
<link rel="stylesheet" href="{% static 'css/add_file.css' %}">
<html lang="ru" translate="no">
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
</head>
<body>
<div class="wrapper">
    <header><a href="/" style="color: black;  text-decoration: none;">Ghost-Checking</a></header>
    <main>
        <form action="{% url 'checking:upload_file' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="Group_3">
            <div class="l_div">
              <div class="l_first"><img src="{% static 'img/icon _document upload.png' %}"></div>
              <div class="l_second"><p>Перенесите файл или</p></div>

              <div class="l_third">
                  <label class="input-file">
                    {{ form.file }}
<!--                <button style="width: 263px; height: 61px; -->
<!--                background-color: #1265B1; border-color: #1265B1;-->
<!--                 color: white;font-size: 35px;-->
<!--                 border-radius: 30px;">-->
<!--                Выбрать</button>-->
                      <span>Выбрать</span>
                  </label>
              </div>

            </div>
            <div class="line"></div>
            <div class="r_div">
              <div class="r_first"><img style="float: left;height: 50%;" src="{% static 'img/Ellipse 3.png' %}"><p>Document.pdf</p></div>
              <div class="r_second"><img style="float: left; height: 50%;" src="{% static 'img/Ellipse 3.png' %}"><p></p>Document.docx</div>
             <input type="submit" value="Отправить" style="margin-top: 178px; width: 263px; height: 61px;
                background-color: #1265B1; border-color: #1265B1;
                 color: white;font-size: 35px;
                 border-radius: 30px;">
            </div>
        </div>
        </form>
    </main>
    <footer>
        <div class="powered_by"><p>powered by ytrewq</p></div>
        <div class="imgs">
            <div class="img_tg"><img src="{% static 'img/icon _tg.png' %}"></div>
            <div class="img_whatapp"><img src="{% static 'img/icon _whatsapp.png' %}"></div>
            <div class="img_instagram"><img src="{% static 'img/icon _instagram.png' %}"></div>
            <div class="img_facebook"><img src="{% static 'img/icon _facebook.png' %}"></div>
        </div>
    </footer>
</div>
</body>
</html>>

ghost_cheking/templates/checking/main.html
<!DOCTYPE html >
<html lang="en" translate="no">
<head>
    <meta charset="UTF-8">
    <title>Проверка гостов</title>
</head>
<body>
    <form action="{% url 'checking:upload_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

ghost_cheking/templates/intro_page/intro.html
{% load static %}
<!DOCTYPE html>
<html lang="en" translate="no">
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script src="{% static 'js/app.js' %}" defer></script>
</head>
<body>

  <section class="layers">
    <div class="layers__container">
      <div class="layers__item layer-1" style="background-image: url({% static 'img/layer-back.png' %});"></div>
      <div class="layers__item layer-2" style="background-image: url({% static 'img/layer-middle.png' %});"></div>
      <div class="layers__item layer-3">
        <div class="hero-content">
          <h1>Проверка документа на  <span>  соответствие ГОСТу </span></h1>
          <div class="hero-content__p"></div>
          <a href="{% url 'checking:upload_file' %}" class="button-start" style="text-decoration: none">Начать</a>
        </div>
    </div>
    <div class="layers__item layer-4" style="background-image: url({% static 'img/layer-front.png' %});"></div>
    </div>
  </section>

 <div style="height: 100vh;"></div>
  
</body>
</html>

ghost_cheking/templates/loading/loading.html
{% load static %}
<!doctype html>
<link rel="stylesheet" href="{% static 'css/loading.css' %}">
<html lang="ru" translate="no">
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
</head>
<body>
<div class="wrapper">
    <header><a href="/" style="color: black;  text-decoration: none;">Ghost-Checking</a></header>
    <main>
        <div class="Group_3">
          <progress value="30" max="100" id="bar"></progress>
          <p class="font_check" id="info"></p>
        </div>
    </main>
    <footer>
        <div class="powered_by"><p>powered by ytrewq</p></div>
        <div class="imgs">
            <div class="img_tg"><img src="{% static 'img/icon _tg.png' %}"></div>
            <div class="img_whatapp"><img src="{% static 'img/icon _whatsapp.png' %}"></div>
            <div class="img_instagram"><img src="{% static 'img/icon _instagram.png' %}"></div>
            <div class="img_facebook"><img src="{% static 'img/icon _facebook.png' %}"></div>
        </div>
    </footer>
</div>
<script>
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
  const arr = ['обзацный отступ', 'шрифт', 'размер шрифтa', 'цвет шрифта', 'размер левого поля', 'размер правого поля'];
  const bar = document.getElementById("bar");
  const info = document.getElementById("info");
  async function demo() {
  let a = 0;
  for (let i = 0; i < 6; i++) {
    a = a + 100 / 6
    console.log(arr[i]);
    bar.value = a;
    info.innerText = "Проверяем " + arr[i];
    await sleep(100);
   }
   window.location.replace("{{ link }}");
  }
    demo();
</script>
</body>
</html>

ghost_cheking/templates/results/all_done.html
{% load static %}
<!doctype html>
<link rel="stylesheet" href="{% static 'css/all_done.css' %}">
<html lang="ru" translate="no">
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
</head>
<body>
<div class="wrapper">
    <header>Ghost-Checking</header>
    <main>
        <div class="Group_3">
            <div>
                <h1 class="q_pravok" style="font-size: 70px">Всё хорошо</h1>
                <p class="q_pravok">документ соответствует ГОСТу</p>
            </div>
        </div>
    </main>
    <footer>
        <div class="powered_by"><p>powered by ytrewq</p></div>
        <div class="imgs">
            <div class="img_tg"><img src="{% static 'img/icon _tg.png' %}"></div>
            <div class="img_whatapp"><img src="{% static 'img/icon _whatsapp.png' %}"></div>
            <div class="img_instagram"><img src="{% static 'img/icon _instagram.png' %}"></div>
            <div class="img_facebook"><img src="{% static 'img/icon _facebook.png' %}"></div>
        </div>
    </footer>
</div>
</body>
</html>

ghost_cheking/templates/results/errors.html
{% load static %}
<!doctype html>
<link rel="stylesheet" href="{% static 'css/errors.css' %}">
<html lang="ru" translate="no">
<head>
  <meta charset="UTF-8">
  <meta name="google" content="notranslate">
</head>
<body>
<div class="wrapper">
    <header><a href="/" style="color: black;  text-decoration: none;">Ghost-Checking</a></header>
    <main>
        <div class="Group_3">
            <p class="q_pravok">Количество правок - 3</p>
            <table>
                <tbody>
                <tr>
                    <td class="td_left">Страница 1</td>
                    <td class="td_right">Обзацный отступ больше допустимого</td>
                </tr>
                <tr>
                    <td class="td_left">Страница 1</td>
                    <td class="td_right">Недопустиный шрифт</td>
                </tr>
                <tr>
                    <td class="td_left">Страница 1</td>
                    <td class="td_right">Размер шрифта меньше допустимого</td>
                </tr>
                </tbody>
            </table>
        </div>
    </main>
    <footer>
        <div class="powered_by"><p>powered by ytrewq</p></div>
        <div class="imgs">
            <div class="img_tg"><img src="{% static 'img/icon _tg.png' %}"></div>
            <div class="img_whatapp"><img src="{% static 'img/icon _whatsapp.png' %}"></div>
            <div class="img_instagram"><img src="{% static 'img/icon _instagram.png' %}"></div>
            <div class="img_facebook"><img src="{% static 'img/icon _facebook.png' %}"></div>
        </div>
    </footer>
</div>
</body>
</html>